### ISSUE TITLE
Win10有问题

### ISSUE THREAD

**Issue by hg1123** [SpaceTimee/Ona-Pix#9]
电脑上装了.net 5.0但是安装软件后依然提示没有.net

**Comment by SpaceTimee** [comment]
这两个都已经安装上了吗: [Runtime](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer), [SDK](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/sdk-5.0.408-windows-x64-installer)

**Comment by hg1123** [comment]
> 这两个都已经安装上了吗: [Runtime](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-5.0.17-windows-x64-installer), [SDK](https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/sdk-5.0.408-windows-x64-installer)

噢噢，装了之后就好了
